version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python:
      version: "3.8"
      install:
        - requirements: requirements.txt

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

