version: 2

build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: true

# Submodules
submodules:
  include:
    - Examples
  recursive: true

search:
  ranking:
    docs/confluence/*: -7
    docs/whitepaper/*: -6
    docs/equiv-check/*: -8
    docs/prover/*: -1
