name: "Pull Request Docs Check"

on: [ pull_request ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        cache: 'pip'
    - run: |
        apt install libenchant-2-2
        pip install -r
        make spelling linkcheck

