name: "spell and link check"

on: [ pull_request ]

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
    - run: sudo apt-get install libenchant-2-2
    - run: pip3 install -r requirements.txt
    - run: make spelling
    - run: |
        find build/spelling -type f | xargs cat > errors.txt
        [[ ! $(cat errors.txt) ]] || (echo && echo "errors:" && cat errors.txt && false)
#    - run: |
#        make linkcheck || (echo && echo "errors:" && cat build/linkcheck/output.txt && false)

